Add article describing the delayed editor initialisation feature
ckeditor/ckeditor4-docs pull request #364
Opened 2021-08-03 12:36 UTC by sculpt0r

https://github.com/ckeditor/ckeditor4-docs/pull/363

2021-08-05 07:26 UTC, sculpt0r commented
@f1ames - article ready for another review:
- Intro is a little bit longer, and I hope descriptive. Anyway, I think that there is no good and plain explanation of this feature without all of the details...
- for a better understanding, I reordered paragraphs, so now we have: a simple intro, then clarification when to use this feature, how it could be used with the use case, and finally some technical stuff.
- correct some misspels

2021-08-06 09:47 UTC, f1ames requested changes
Ok, looks good 👍 

Only some really minor things to polish.

2021-08-06 09:47 UTC, f1ames commented on docs/features/delayed_creation/README.md
> +- The last interval check may happen milliseconds before the user clicks the button. The default timeout is small enough, that there will be no flickering effect, but still, there will be a slight de
Could we mention the config which can be used to change default interval here?

2021-08-10 05:32 UTC, sculpt0r commented on docs/features/delayed_creation/README.md
> +Delayed editor creation starts when you invoke casual [`replace()`](../api/CKEDITOR.html#method-replace) or [`inline()`](../api/CKEDITOR.html#method-inline) methods, but the editor is not created imm
I rewrite the sentence. I doubled the information that the proper config is also required, but for clarity - it may be not quite good place for that.

2021-08-10 05:56 UTC, sculpt0r commented
@f1ames - ready for another review. Corrected accordingly to all your suggestions.

2021-08-10 07:39 UTC, f1ames approved these changes
LGTM 👍 

@godai78 could you take a look too?

2021-08-10 07:39 UTC, f1ames commented on docs/features/delayed_creation/README.md
> +- The interval checks might be adjusted with the [delayIfDetached_interval option](../api/CKEDITOR_config.html#cfg-delayIfDetached_interval). However, if you make it shorter - performance might be af
```suggestion
- The interval checks might be adjusted with the [delayIfDetached_interval option](../api/CKEDITOR_config.html#cfg-delayIfDetached_interval). However, if you make it shorter - performance might be affected. If you lengthen the interval - the delay might start to be visible.
```

2021-08-10 08:19 UTC, godai78 approved these changes

2021-08-11 10:20 UTC, f1ames commented
Rebased onto latest `major`.

2021-08-11 10:20 UTC, merged