Add Error Code Reference to flash plugin
ckeditor/ckeditor4-docs pull request #372
Opened 2021-09-10 06:27 UTC by KarolDawidziuk

Regarding to removing `flash` plugin from our ecosystem I've added `Error Code Reference` to flash plugin.

Closes [#4877](https://github.com/ckeditor/ckeditor4/issues/4877).

2021-09-28 14:08 UTC, jacekbogdanski requested changes
The error message should be more generic, that's why I proposed to use `editor-plugin-deprecated` instead of `flash-plugin-deprecated`. I also see that we are actually using `plugin` as a plugin name for other error codes, not `pluginName`. We have to fix that issue on `major` branch as flash plugin removal PR has been already merged. @KarolDawidziuk could you prepare PR for that? We don't need a separate issue for such a small change, just make sure to update both flash plugin code and tests.

2021-09-28 14:08 UTC, jacekbogdanski commented on docs/guide/dev/deep_dive/errors/README.md
> +
```suggestion
## editor-plugin-deprecated

* Location: `core/editor.js`
* Description: The plugin has been deprecated and should no longer be used.
* Additional data:
	* `plugin`: The name of the plugin that has been deprecated.
```

2021-09-29 07:01 UTC, KarolDawidziuk commented
Thanks, @jacekbogdanski  for the review.
It's ready for another one.

Changes:
 * updated `error code reference` to more generic.
 * created [PR](https://github.com/ckeditor/ckeditor4/pull/4917) in `ckeditor4` repo with swapping  `pluginName` to `plugin` like in the other error codes.

2021-09-29 08:02 UTC, jacekbogdanski approved these changes

2021-09-29 08:03 UTC, merged